# Generated by Django 4.2.26 on 2025-11-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keddy_mailer', '0034_emailtracking_error_message_emailtracking_is_failed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=100)),
                ('max_followups', models.IntegerField(default=3)),
                ('days_between', models.IntegerField(default=2)),
                ('trigger_time', models.TimeField(default='11:00')),
                ('stop_on_open', models.BooleanField(default=True)),
                ('stop_on_click', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('current_sequence', models.IntegerField(default=0)),
                ('total_emails_sent', models.IntegerField(default=0)),
                ('total_credits_used', models.IntegerField(default=0)),
                ('additional_opens', models.IntegerField(default=0)),
                ('additional_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_campaigns', to='keddy_mailer.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_recipients', models.IntegerField(default=0)),
                ('total_followups_sent', models.IntegerField(default=0)),
                ('total_credits_used', models.IntegerField(default=0)),
                ('overall_open_rate', models.FloatField(default=0.0)),
                ('overall_click_rate', models.FloatField(default=0.0)),
                ('additional_conversions', models.IntegerField(default=0)),
                ('sequence_1_sent', models.IntegerField(default=0)),
                ('sequence_1_opens', models.IntegerField(default=0)),
                ('sequence_1_clicks', models.IntegerField(default=0)),
                ('sequence_2_sent', models.IntegerField(default=0)),
                ('sequence_2_opens', models.IntegerField(default=0)),
                ('sequence_2_clicks', models.IntegerField(default=0)),
                ('sequence_3_sent', models.IntegerField(default=0)),
                ('sequence_3_opens', models.IntegerField(default=0)),
                ('sequence_3_clicks', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup_campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='followups.followupcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('sequence_number', models.IntegerField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('credit_deducted', models.BooleanField(default=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('open_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('click_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followup_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followups.followupcampaign')),
                ('original_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keddy_mailer.emailtracking')),
            ],
            options={
                'indexes': [models.Index(fields=['followup_campaign', 'recipient'], name='followups_f_followu_e340b7_idx'), models.Index(fields=['is_active'], name='followups_f_is_acti_b06f46_idx')],
                'unique_together': {('followup_campaign', 'recipient', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='FollowUpSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('days_after_previous', models.IntegerField(default=2)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followup_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='followups.followupcampaign')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keddy_mailer.template')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('followup_campaign', 'sequence_number')},
            },
        ),
    ]
