# Generated by Django 4.2.21 on 2025-06-27 09:29

from django.db import migrations, models
import django.db.models.deletion
import keddy_mailer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(default=keddy_mailer.models.generate_alphanumeric_id, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='email_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('list_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='email_lists/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=130)),
                ('password', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=120)),
                ('smtp_server', models.CharField(max_length=120, unique=True)),
                ('emails_per_hour', models.IntegerField()),
                ('security', models.CharField(max_length=20)),
                ('is_active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reply_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('placeholder_text', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(max_length=100)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keddy_mailer.email_list')),
                ('smtp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keddy_mailer.smtpserver')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keddy_mailer.template')),
            ],
        ),
    ]
