# Generated by Django 4.2.21 on 2025-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
