# Generated by Django 4.2.21 on 2025-06-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0002_campaign_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
