# Generated by Django 4.2.21 on 2025-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0003_campaign_is_sent_campaign_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
