# Generated by Django 4.2.21 on 2025-07-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0004_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='custom_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='manual_recipients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
