# Generated by Django 4.2.21 on 2025-07-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0005_campaign_custom_template_campaign_manual_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keddy_mailer.email_list'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keddy_mailer.template'),
        ),
    ]
