# Generated by Django 4.2.21 on 2025-07-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0007_emailtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='cta_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
