# Generated by Django 4.2.21 on 2025-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0008_emailtracking_cta_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtracking',
            name='cta_text',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cta_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
