# Generated by Django 4.2.21 on 2025-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0010_unsubscribedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpserver',
            name='smtp_server',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='smtpserver',
            name='username',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
