# Generated by Django 4.2.21 on 2025-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0011_alter_smtpserver_smtp_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_credit_limit',
            field=models.BigIntegerField(default=200),
        ),
    ]
