# Generated by Django 4.2.21 on 2025-07-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0012_customuser_email_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='smtp_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keddy_mailer.smtpserver'),
        ),
    ]
