# Generated by Django 4.2.21 on 2025-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0013_alter_campaign_smtp_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
