# Generated by Django 4.2.21 on 2025-07-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0016_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
