# Generated by Django 4.2.21 on 2025-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0017_remove_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
