# Generated by Django 4.2.21 on 2025-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0018_alter_template_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='used_email_credit',
            field=models.BigIntegerField(default=0),
        ),
    ]
