# Generated by Django 4.2.21 on 2025-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0019_customuser_used_email_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/default_bw.png', null=True, upload_to='profile_pics/'),
        ),
    ]
