# Generated by Django 4.2.21 on 2025-07-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0021_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='attachments',
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_attachments', to='keddy_mailer.campaign')),
            ],
        ),
    ]
