# Generated by Django 4.2.21 on 2025-07-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0022_remove_campaign_attachments_campaignattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_html_template',
            field=models.BooleanField(default=True),
        ),
    ]
