# Generated by Django 4.2.21 on 2025-07-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0023_campaign_is_html_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_html_template',
        ),
        migrations.AddField(
            model_name='campaign',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.DeleteModel(
            name='CampaignAttachment',
        ),
    ]
