# Generated by Django 4.2.21 on 2025-07-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0024_remove_campaign_is_html_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='keddy_mailer.campaign')),
            ],
        ),
    ]
