# Generated by Django 4.2.21 on 2025-07-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0025_campaignattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cta_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
