# Generated by Django 4.2.21 on 2025-07-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0026_campaign_cta_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='placeholder_text',
            new_name='preheader',
        ),
    ]
