# Generated by Django 4.2.21 on 2025-07-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0027_rename_placeholder_text_campaign_preheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_count', models.IntegerField(default=1)),
                ('smtp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='keddy_mailer.smtpserver')),
            ],
        ),
    ]
