# Generated by Django 4.2.21 on 2025-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0028_smtpusagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_credit_limit',
            field=models.BigIntegerField(default=0),
        ),
    ]
