# Generated by Django 4.2.21 on 2025-07-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0030_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
