# Generated by Django 4.2.7 on 2025-10-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0033_remove_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
