# Generated by Django 4.2.7 on 2025-11-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keddy_mailer', '0034_emailtracking_error_message_emailtracking_is_failed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLineFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='subject_lines/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='used_subject_line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject_line_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='keddy_mailer.subjectlinefile'),
        ),
    ]
